routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\admin\RoleController;


Route::get('', [HomeController::class, 'index'] )->middleware('can:admin.home')->name('admin.home');

Route::resource('users', UserController::class)->only(['index','edit','update'])->names('admin.users');
Route::resource('roles', RoleController::class)->Except('show')->names('admin.roles');

Route::resource('categories', CategoryController::class)->Except('show')->names('admin.categories');
Route::resource('tags', TagController::class)->Except('show')->names('admin.tags');
Route::resource('posts', PostController::class)->Except('show')->names('admin.posts');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;


Route::get('/', [PostController::class,'index'])->name('posts.index');
Route::get('posts/{post}', [PostController::class,'show'])->name('posts.show');
Route::get('categories/{category}', [PostController::class,'category'])->name('posts.category');
Route::get('tags/{tag}', [PostController::class,'tag'])->name('posts.tag');

Route::middleware([ 'auth:sanctum',  config('jetstream.auth_session'),    'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Http/Livewire/Admin/PostsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Post;
use Livewire\Component;
use Livewire\WithPagination;

class PostsIndex extends Component
{
    use WithPagination;
    protected $paginationTheme  = "bootstrap";

    public $search;

    public function updatingSearch(){
        $this->resetPage();
    }


    public function render()
    {
        $posts = Post::where('user_id', auth()->user()->id)
        ->where('name','like','%'. $this->search . '%')
        ->latest('id'
        )->paginate() ;

        return view('livewire.admin.posts-index', compact('posts'));
    }
}

app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;

use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;
    protected $paginationTheme  = "bootstrap";
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }


    public function render()
    {
        $users = User::where('name','like','%'. $this->search . '%')
        ->orwhere('email','like','%'. $this->search . '%')
        ->paginate();
        return view('livewire.admin.users-index', compact('users'));
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use App\Models\Category;
use Livewire\Component;

class Navigation extends Component
{
    public function render()
    {
        $categories= Category::all();
        return view('livewire.navigation', compact('categories'));
    }
}

resources/views/livewire/admin/posts-index.blade.php
<div class="card">

    <div class="card-header">
        <input wire:model="search" class="form-control" type="text" name="" id="">
    </div>
    @if ($posts->count())
        <div class="card-body">
            <table class="table table-striped">

                <thead>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th colspan=2></th>

                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td>{{ $post->id }}</td>
                            <td>{{ $post->name }}</td>
                            <td width="10px">
                                <a href="{{ route('admin.posts.edit', $post) }}" class="btn btn-primary btn-sm">
                                    Editar
                                </a>
                            </td>
                            <td width="10px">
                                <form action="{{ route('admin.posts.destroy', $post) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-sm" type="submit"
                                        onclick="return confirm('Desea eliminar ?')">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>

            </table>

        </div>
        <div class="card-footer">
            {{ $posts->links() }}
        </div>
    @else
        <div class="card-body">
            <strong>
                No hay ningun regostro ...
            </strong>
        </div>


    @endif


</div>

resources/views/livewire/admin/users-index.blade.php
<div>
    {{-- Close your eyes. Count to one. That is how long forever feels. --}}

    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" type="text" name="" id=""
                placeholder="Ingrese nombre o correo de usuario ">
        </div>

        @if ($users->count())
            <div class="card-body">
                <table class="table table-striped">

                    <thead>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Email</th>
                        <th colspan=2></th>

                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td width="10px">
                                    <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary btn-sm">
                                        Editar
                                    </a>
                                </td>
                              
                            </tr>
                        @endforeach
                    </tbody>

                </table>

            </div>
            <div class="card-footer">
                {{ $users->links() }}
            </div>
        @else
            <div class="card-body">
                <strong>
                    No hay ningun regostro ...
                </strong>
            </div>


        @endif
    </div>
</div>